# ANALYSE EXPLORATOIRE DES DONNEES EVENTS SUR LE BENIN

## Importation et chagement des packages

In [4]:
import pandas as pd
from pandasql import sqldf

In [ ]:

# Basic import
df = pd.read_parquet('../data/raw/eventsBenin.parquet')

# Specific engine (requires pyarrow or fastparquet)
# df = pd.read_parquet('data/raw/eventsBenin.parquet', engine='pyarrow')

In [36]:
df.sample(5)

,MonthYear,Actor1Name,Actor1CountryCode,Actor1Type1Code,Actor2Name,Actor2CountryCode,Actor2Type1Code,EventRootCode,QuadClass,GoldsteinScale,NumMentions,NumArticles,AvgTone,ActionGeo_CountryCode,ActionGeo_FullName,ActionGeo_Lat,ActionGeo_Long,rn,EventName
5938,202511,ADMINISTRATION,None,GOV,BENIN,BEN,GOV,13,3,-4.4,10,10,-0.707547,BN,Benin,9.50000,2.25000,443,THREATEN
11159,202501,BENIN,BEN,None,None,None,None,01,1,0.0,10,10,4.081633,BN,"Ouidah, Atlantique, Benin",6.36307,2.08506,565,MAKE PUBLIC STATEMENT
14209,202511,BENIN,BEN,None,AFRICA,AFR,None,04,1,1.0,1,1,8.465608,BN,Benin,9.50000,2.25000,1404,CONSULT
13384,202512,GUINEA BISSAU,GNB,None,GOODLUCK JONATHAN,NGA,GOV,01,1,0.0,2,2,-2.106847,BN,Benin,9.50000,2.25000,2325,MAKE PUBLIC STATEMENT
1745,202602,MILITARY PATROL,None,MIL,NIGERIAN,NGA,None,19,4,-10.0,1,1,-9.438776,BN,Benin,9.50000,2.25000,1338,FIGHT

In [37]:

# Fonction pour executer le code SQL
pysqldf = lambda q: sqldf(q, globals())

# SQL test Liste des mois disponibles
query = "SELECT DISTINCT(MonthYear) AS 'Mois' FROM df ORDER BY MonthYear;"

result = pysqldf(query)

In [38]:
result.sample()

     Mois
2  202503

In [34]:
cameo_event_code = pd.read_csv('../data/raw/CAMEO.eventcodes.txt', sep='\t', dtype=str)
cameo = cameo_event_code.set_index("CAMEOEVENTCODE")["EVENTDESCRIPTION"].to_dict()
df["EventName"] = df["EventRootCode"].map(cameo).fillna("Other")

In [54]:
pysqldf("SELECT EventName, COUNT(*) AS 'Nombre devenements' FROM df GROUP BY EventName ORDER BY 2 DESC")

                           EventName  Nombre devenements
0                            CONSULT                7235
1              MAKE PUBLIC STATEMENT                4742
2   ENGAGE IN DIPLOMATIC COOPERATION                3919
3                             APPEAL                2175
4                         DISAPPROVE                1794
5                             COERCE                1677
6                              FIGHT                1640
7        EXPRESS INTENT TO COOPERATE                1230
8                              YIELD                1041
9                        PROVIDE AID                 990
10                            REJECT                 673
11                           ASSAULT                 607
12    ENGAGE IN MATERIAL COOPERATION                 548
13                          THREATEN                 519
14                       INVESTIGATE                 514
15                           PROTEST                 444
16                            DEMAND                 330
17             EXHIBIT FORCE POSTURE                 296
18                  REDUCE RELATIONS                 171